---

- name: Clean up previous k3s-init
  ansible.builtin.systemd:
    name: k3s-init
    state: stopped
  failed_when: false

- name: Clean up previous k3s-init
  ansible.builtin.command: systemctl reset-failed k3s-init
  failed_when: false
  changed_when: false
  args:
    warn: false  # The ansible systemd module does not support reset-failed

- name: Init cluster inside the transient k3s-init service
  ansible.builtin.command:
    cmd: "systemd-run -p RestartSec=2 \
                      -p Restart=on-failure \
                      --unit=k3s-init \
                      k3s server {{ server_init_args }}"
    creates: /etc/systemd/system/k3s.service

- name: Cluster verification
  block:
    - name: Verify that all nodes actually joined
      ansible.builtin.command:
        cmd: k3s kubectl get nodes -l "node-role.kubernetes.io/master=true" -o=jsonpath="{.items[*].metadata.name}"
      register: nodes
      until: nodes.rc == 0 and (nodes.stdout.split() | length) == (groups['master'] | length)
      retries: 20
      delay: 10
      changed_when: false
  always:
    - name: Kill the temporary service used for initialization
      ansible.builtin.systemd:
        name: k3s-init
        state: stopped
      failed_when: false
  when: not ansible_check_mode
