---

- name: Set cluster_init to false
  ansible.builtin.set_fact:
    cluster_init: false

- name: Copy K3s config
  ansible.builtin.template:
    src: config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0600'

- name: Enable and start K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: Create directory .kube
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: '0700'

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: '0600'

- name: Replace localhost by api server
  ansible.builtin.command: >-
    k3s kubectl config set-cluster default
      --server=https://{{ k3s_api_server }}:6443
      --kubeconfig ~{{ ansible_user }}/.kube/config
  changed_when: true

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link

- name: Create local directory .kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true
  become: false

- name: Copy config file to local user home directory
  ansible.builtin.fetch:
    src: ~{{ ansible_user }}/.kube/config
    dest: ~/.kube/config
    flat: true
  delegate_to: "{{ groups['server'][0] }}"
  run_once: true
  become: false
