---

- name: Copy K3s service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: '0644'

- name: Create K3s config directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0600'

- name: Copy K3s config
  ansible.builtin.template:
    src: agent.config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    owner: root
    group: root
    mode: '0600'

- name: Enable and start K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true
