---

- name: Import prerequisite tasks
  ansible.builtin.import_tasks: prerequisites.yml

- name: Import download tasks
  ansible.builtin.import_tasks: download.yml

- name: Import k3s tasks
  ansible.builtin.import_tasks: k3s.yml

- name: Import reset tasks
  ansible.builtin.import_tasks: reset.yml
  tags:
    - never
    - uninstall
