---

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Activate cgroup support
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: Reboot system

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Flush iptables before changing to iptables-legacy
  ansible.builtin.iptables:
    flush: true
  changed_when: false   # iptables flush always returns changed

- name: Change to iptables-legacy
  community.general.alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy

- name: Change to ip6tables-legacy
  community.general.alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy
