---

- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  ignore_errors: true
  with_items:
    - k3s

- name: Kill container shim
  ansible.builtin.command: pkill -9 -f "k3s/data/[^/]+/bin/containerd-shim-runc"
  register: pkill_containerd_shim_runc
  changed_when: "pkill_containerd_shim_runc.rc == 0"
  failed_when: false

- name: Unmount k3s filesystems
  ansible.builtin.include_tasks: unmount.yml
  with_items:
    - /run/k3s
    - /var/lib/rancher/k3s
    - /var/lib/kubelet/pods
    - /var/lib/kubelet/plugins
    - /run/netns/cni-
  loop_control:
    loop_var: mounted_fs

- name: Remove service files, binaries and data
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /usr/local/bin/k3s
    - /etc/systemd/system/k3s.service
    - /etc/rancher/k3s
    - /var/lib/kubelet
    - /var/lib/rancher/k3s

- name: Reset network
  ansible.builtin.import_tasks: reset_network.yml

- name: Remove CNI binaries
  ansible.builtin.file:
    state: absent
    path: /var/lib/cni/

- name: Reset iptables
  ansible.builtin.import_tasks: reset_iptables.yml

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true
