---

- name: Get network namespaces
  ansible.builtin.command:
    cmd: ip netns
  register: namespaces
  changed_when: false

- name: Remove CNI namespaces
  community.general.ip_netns:
    name: "{{ item | split(' ') | first }}"
    state: absent
  when: "'cni-' in item"
  loop: "{{ namespaces.stdout_lines }}"

- name: Get network interfaces
  ansible.builtin.command:
    cmd: ip link show master cni0
  register: interfaces
  changed_when: false
  ignore_errors: true

- name: Delete cni0 network interfaces
  ansible.builtin.command:
    cmd: ip link delete "{{ item | split('@') | first | split(' ') | last }}"
  when: "'master cni0' in item"
  loop: "{{ interfaces.stdout_lines }}"
  changed_when: false

- name: Delete cni, flannel and kube network interfaces
  ansible.builtin.command:
    cmd: ip link delete "{{ item }}"
  register: result
  loop:
    - cni0
    - flannel.1
    - flannel-v6.1
    - kube-ipvs0
    - flannel-wg
    - flannel-wg-v6
  changed_when: false
  failed_when: '"Error" in result.stdout'
